apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rsaKeys.existingSecret }}
type: Opaque
data:
  private.pem: "{{ .Files.Get "keys/private.pem" | b64enc }}"
  public.pem: "{{ .Files.Get "keys/public.pem" | b64enc }}"
