apiVersion: v1
kind: Service
metadata:
  name: {{ include "naviam-license.fullname" . }}-api
  labels:
    {{- include "naviam-license.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "naviam-license.selectorLabels" . | nindent 4 }}
    component: api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "naviam-license.fullname" . }}-web
  labels:
    {{- include "naviam-license.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "naviam-license.selectorLabels" . | nindent 4 }}
    component: web
